In [1]:
print("Hello World")

Hello World


In [2]:
2**4

16

In [3]:
2*3/2

3.0

In [4]:
type(33.05)

float

In [6]:
type("true")

str

In [7]:
type("fuck_everyone")

str

In [8]:
type(2)

int

In [11]:
a=2
b=5
sum=a+b
print(sum)

7


In [16]:
age_a=20
age_b=35
difference=age_b-age_a
print(difference)

15


In [20]:
print("I am a python beginner\n and I am learning at a fast pace")

I am a python beginner
 and I am learning at a fast pace


In [21]:
print("I am a python beginner\t and I am learning at a fast pace")

I am a python beginner	 and I am learning at a fast pace


In [24]:
word="vocabulary"
word[0:4]

'voca'

In [25]:
15>30

False

In [26]:
30>15

True

In [2]:
basic="hello world i am still a beginner pythonista"
basic.upper()

'HELLO WORLD I AM STILL A BEGINNER PYTHONISTA'

In [4]:
basic ="MY NAME IS FAIZAT PEOPLE"
basic.lower()

'my name is faizat people'

In [8]:
import numpy
import numpy as np

In [9]:
x= np.array([1, 2, 3, 4, 5])
y= np.array([9,18])
print(x)
print("the shape of x is",x.shape)

print(y)
print("the shape of y is",y.shape)

[1 2 3 4 5]
the shape of x is (5,)
[ 9 18]
the shape of y is (2,)


In [18]:
age = 20
age2 =30
difference = age2 - age
print("the difference is ",difference)
print(age)
print("the age of our tutor is",age)
print(age2)
print("the age of mr abanikanda is",age2)

the difference is  10
20
the age of our tutor is 20
30
the age of mr abanikanda is 30


In [23]:
user_name="temmy_gem"
password="12334"
print ("welcome {} and your password is {}".format (user_name, password))

welcome temmy_gem and your password is 12334


In [29]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(w,'\n')
print('The shape of w is' , w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] 

The shape of w is (2, 3, 3)


In [30]:
user_name=input("please enter your username:")
password=input("please enter your password:")
print ("welcome {} and your password is {}".format (user_name, password))

please enter your username:temmy_gem
please enter your password:12334
welcome temmy_gem and your password is 12334


In [32]:
a= input("please enter a decimal value:")
b=input("please enter a whole value:")
sum = float(a) + int(b)
print ("sum: "+ str(sum))

please enter a decimal value:0.57
please enter a whole value:32
sum: 32.57


In [37]:
c= input("please enter your tutor's age:")
d= input("please enter mr abanikanda's age")
difference = int(d) - int (c)
print ("difference:" + str(difference))

please enter your tutor's age:20
please enter mr abanikanda's age35
difference:15
